// Nepal administrative divisions: provinces -> districts -> municipalities/rural
// municipalities (753 local levels, 2017 federal restructuring). Sourced from
// https://github.com/sagautam5/local-states-nepal (English dataset).

export const NEPAL_PROVINCES = [
  "Koshi Province",
  "Madhesh Province",
  "Bagmati Province",
  "Gandaki Province",
  "Lumbini Province",
  "Karnali Province",
  "Sudurpaschim Province"
];

export const DISTRICTS_BY_PROVINCE = {
  "Koshi Province": [
    "Bhojpur",
    "Dhankuta",
    "Ilam",
    "Jhapa",
    "Khotang",
    "Morang",
    "Okhaldhunga",
    "Panchthar",
    "Sankhuwasabha",
    "Solukhumbu",
    "Sunsari",
    "Taplejung",
    "Terhathum",
    "Udayapur"
  ],
  "Madhesh Province": [
    "Bara",
    "Dhanusha",
    "Mahottari",
    "Parsa",
    "Rautahat",
    "Saptari",
    "Sarlahi",
    "Siraha"
  ],
  "Bagmati Province": [
    "Bhaktapur",
    "Chitwan",
    "Dhading",
    "Dolakha",
    "Kathmandu",
    "Kavrepalanchok",
    "Lalitpur",
    "Makwanpur",
    "Nuwakot",
    "Ramechhap",
    "Rasuwa",
    "Sindhuli",
    "Sindhupalchok"
  ],
  "Gandaki Province": [
    "Baglung",
    "Gorkha",
    "Kaski",
    "Lamjung",
    "Manang",
    "Mustang",
    "Myagdi",
    "Nawalpur",
    "Parbat",
    "Syangja",
    "Tanahun"
  ],
  "Lumbini Province": [
    "Arghakhanchi",
    "Banke",
    "Bardiya",
    "Dang",
    "Eastern Rukum",
    "Gulmi",
    "Kapilvastu",
    "Palpa",
    "Parasi",
    "Pyuthan",
    "Rolpa",
    "Rupandehi"
  ],
  "Karnali Province": [
    "Dailekh",
    "Dolpa",
    "Humla",
    "Jajarkot",
    "Jumla",
    "Kalikot",
    "Mugu",
    "Salyan",
    "Surkhet",
    "Western Rukum"
  ],
  "Sudurpaschim Province": [
    "Achham",
    "Baitadi",
    "Bajhang",
    "Bajura",
    "Dadeldhura",
    "Darchula",
    "Doti",
    "Kailali",
    "Kanchanpur"
  ]
};

export const MUNICIPALITIES_BY_DISTRICT = {
  "Bhojpur": [
    "Aamchok",
    "Arun",
    "Bhojpur",
    "Hatuwagadhi",
    "Pauwadungma",
    "Ramprasad Rai",
    "Salpasilichho",
    "Shadanand",
    "Tyamke Maiyum"
  ],
  "Dhankuta": [
    "Chaubise",
    "Chhathar Jorpati",
    "Dhankuta",
    "Mahalaxmi",
    "Pakhribas",
    "Sahidbhumi",
    "Sangurigadhi"
  ],
  "Ilam": [
    "Chulachuli",
    "Deumai",
    "Ilam",
    "Mai",
    "Maijogmai",
    "Mangsebung",
    "Phakphokthum",
    "Rong",
    "Sandakpur",
    "Suryodaya"
  ],
  "Jhapa": [
    "Arjundhara",
    "Barhadashi",
    "Bhadrapur",
    "Birtamod",
    "Buddha Shanti",
    "Damak",
    "Gauradaha",
    "Gaurigunj",
    "Haldibari",
    "Jhapa",
    "Kachankawal",
    "Kamal",
    "Kankai",
    "Mechinagar",
    "Shivasatakshi"
  ],
  "Khotang": [
    "Aiselukharka",
    "Barahpokhari",
    "Diktel Rupakot Majhuwagadhi",
    "Diprung Chuichumma",
    "Halesi Tuwachung",
    "Jantedhunga",
    "Kepilasgadhi",
    "Khotehang",
    "Rawa Besi",
    "Sakela"
  ],
  "Morang": [
    "Belbari",
    "Biratnagar",
    "Budi Ganga",
    "Dhanpalthan",
    "Gramthan",
    "Jahada",
    "Kanepokhari",
    "Katahari",
    "Kerabari",
    "Letang",
    "Miklajung",
    "Pathari Shanischare",
    "Rangeli",
    "Ratuwamai",
    "Sunawarshi",
    "Sundar Haraicha",
    "Urlabari"
  ],
  "Okhaldhunga": [
    "Champadevi",
    "Chisankhugadhi",
    "Khiji Demba",
    "Likhu",
    "Manebhanjyang",
    "Molung",
    "Siddhicharan",
    "Sunkoshi"
  ],
  "Panchthar": [
    "Hilihang",
    "Kummayak",
    "Miklajung",
    "Phalelung",
    "Phalgunanda",
    "Phidim",
    "Tumbewa",
    "Yangwarak"
  ],
  "Sankhuwasabha": [
    "BhotKhola",
    "Chainpur",
    "Chichila",
    "Dharmadevi",
    "Khandbari",
    "Madi",
    "Makalu",
    "Panchkhapan",
    "Sabhapokhari",
    "Silichong"
  ],
  "Solukhumbu": [
    "Khumbu PasangLhamu",
    "Likhu Pike",
    "Maha Kulung",
    "Mapya Dudhkoshi",
    "Necha Salyan",
    "Solu Dudhkunda",
    "Sotang",
    "Thulung Dudhkoshi"
  ],
  "Sunsari": [
    "BarahaKshetra",
    "Barju",
    "Bhokraha Narsingh",
    "Dewangunj",
    "Dharan",
    "Duhabi",
    "Gadhi",
    "Harinagar",
    "Inaruwa",
    "Itahari",
    "Koshi",
    "Ramdhuni"
  ],
  "Taplejung": [
    "Aathrai Triveni",
    "Maiwa Khola",
    "Meringden",
    "Mikwa Khola",
    "Pathibhara Yangwarak",
    "Phaktanglung",
    "Phungling",
    "Sidingwa",
    "Sirijangha"
  ],
  "Terhathum": [
    "Aathrai",
    "Chhathar",
    "Laligurans",
    "Menchayayem",
    "Myanglung",
    "Phedap"
  ],
  "Udayapur": [
    "Belaka",
    "Chaudandigadhi",
    "Katari",
    "Limchungbung",
    "Rautamai",
    "Tapli",
    "Triyuga",
    "Udayapurgadhi"
  ],
  "Parsa": [
    "Bahudarmai",
    "Bindabasini",
    "Birgunj",
    "Chhipaharmai",
    "Dhobini",
    "Jagarnathpur",
    "Jirabhawani",
    "Kalikamai",
    "Pakaha Mainpur",
    "Parsagadhi",
    "Paterwa Sugauli",
    "Pokhariya",
    "Sakhuwa Prasauni",
    "Thori"
  ],
  "Bara": [
    "Adarsh Kotwal",
    "Baragadhi",
    "Bishrampur",
    "Devtal",
    "Jitpur Simara",
    "Kalaiya",
    "Karaiyamai",
    "Kolhabi",
    "Mahagadhimai",
    "Nijgadh",
    "Pacharauta",
    "Parwanipur",
    "Pheta",
    "Prasauni",
    "Simaraungadh",
    "Suwarna"
  ],
  "Rautahat": [
    "Baudhimai",
    "Brindaban",
    "Chandrapur",
    "Dewahi Gonahi",
    "Durga Bhagwati",
    "Gadhimai",
    "Gaur",
    "Gujara",
    "Guruda",
    "Ishanath",
    "Katahariya",
    "Madhav Narayan",
    "Maulapur",
    "Paroha",
    "Phatuwa Bijayapur",
    "Rajdevi",
    "Rajpur",
    "Yamunamai"
  ],
  "Sarlahi": [
    "Bagmati",
    "Balara",
    "Barahathwa",
    "Basbariya",
    "Bisnu",
    "Brahampuri",
    "Chakraghatta",
    "Chandranagar",
    "Dhankaul",
    "Godaita",
    "Haripur",
    "Haripurwa",
    "Hariwan",
    "Ishowrpur",
    "Kabilasi",
    "Kaudena",
    "Lalbandi",
    "Malangawa",
    "Parsa",
    "Ramnagar"
  ],
  "Siraha": [
    "Arnama",
    "Aurahi",
    "Bariyarpatti",
    "Bhagwanpur",
    "Bishnupur",
    "Dhangadhimai",
    "Golbazar",
    "Kalyanpur",
    "Karjanha",
    "Lahan",
    "Lakshmipur Patari",
    "Mirchaiya",
    "Naraha",
    "Navarajpur",
    "SakhuwanankarKatti",
    "Siraha",
    "Sukhipur"
  ],
  "Dhanusha": [
    "Aaurahi",
    "Bateshwar",
    "Bideha",
    "Chhireshwarnath",
    "Dhanauji",
    "Dhanushadham",
    "Ganeshman Charnath",
    "Hansapur",
    "Janaknandani",
    "Janakpurdham",
    "Kamala",
    "Lakshminya",
    "Mithila",
    "MithilaBihari",
    "Mukhiyapatti Musharniya",
    "Nagarain",
    "Sabaila",
    "Sahidnagar"
  ],
  "Saptari": [
    "Agnisaira Krishnasavaran",
    "Balan-Bihul",
    "Bishnupur",
    "Bodebarsain",
    "Chhinnamasta",
    "Dakneshwori",
    "Hanumannagar Kankalini",
    "Kanchanrup",
    "Khadak",
    "Mahadeva",
    "Rajbiraj",
    "Rajgadh",
    "Rupani",
    "Saptakoshi",
    "Shambhunath",
    "Surunga",
    "Tilathi Koiladi",
    "Tirhut"
  ],
  "Mahottari": [
    "Aaurahi",
    "Balawa",
    "Bardibas",
    "Bhangaha",
    "Ekdara",
    "Gaushala",
    "Jaleshor",
    "Loharpatti",
    "Mahottari",
    "Manara Shiswa",
    "Matihani",
    "Pipara",
    "Ramgopalpur",
    "Samsi",
    "Sonama"
  ],
  "Bhaktapur": [
    "Bhaktapur",
    "Changunarayan",
    "Madhyapur Thimi",
    "Suryabinayak"
  ],
  "Chitwan": [
    "Bharatpur",
    "Ichchhakamana",
    "Kalika",
    "Khairhani",
    "Madi",
    "Rapti",
    "Ratnagar"
  ],
  "Dhading": [
    "Benighat Rorang",
    "Dhunibeshi",
    "Gajuri",
    "Galchhi",
    "Gangajamuna",
    "Jwalamukhi",
    "Khaniyabas",
    "Netrawati Dabjong",
    "Nilkantha",
    "Rubi Valley",
    "Siddhalek",
    "Thakre",
    "Tripurasundari"
  ],
  "Dolakha": [
    "Baiteshowr",
    "Bhimeswor",
    "Bigu",
    "Gaurishankar",
    "Jiri",
    "Kalinchok",
    "Melung",
    "Sailung",
    "Tamakoshi"
  ],
  "Kathmandu": [
    "Budhalikantha",
    "Chandragiri",
    "Dakshinkali",
    "Gokarneshwar",
    "Kageshwari-Manohara",
    "Kathmandu",
    "Kirtipur",
    "Nagarjun",
    "Shankharapur",
    "Tarakeshwar",
    "Tokha"
  ],
  "Kavrepalanchok": [
    "Banepa",
    "Bethanchok",
    "Bhumlu",
    "Chauri Deurali",
    "Dhulikhel",
    "Khani Khola",
    "Mahabharat",
    "Mandandeupur",
    "Namobuddha",
    "Panauti",
    "Panchkhal",
    "Roshi",
    "Temal"
  ],
  "Lalitpur": [
    "Bagmati",
    "Godawari",
    "Konjyosom",
    "Lalitpur",
    "Mahalaxmi",
    "Mahankal"
  ],
  "Makwanpur": [
    "Bagmati",
    "Bakaiya",
    "Bhimphedi",
    "Hetauda",
    "Indrasarowar",
    "Kailash",
    "Makawanpurgadhi",
    "Manahari",
    "Raksirang",
    "Thaha"
  ],
  "Nuwakot": [
    "Belkotgadhi",
    "Bidur",
    "Dupcheshwar",
    "Kakani",
    "Kispang",
    "Likhu",
    "Myagang",
    "Panchakanya",
    "Shivapuri",
    "Suryagadhi",
    "Tadi",
    "Tarkeshwar"
  ],
  "Ramechhap": [
    "Doramba",
    "Gokulganga",
    "Khandadevi",
    "LikhuTamakoshi",
    "Manthali",
    "Ramechhap",
    "Sunapati",
    "Umakunda"
  ],
  "Rasuwa": [
    "Gosaikunda",
    "Kalika",
    "Naukunda",
    "Parbatikunda",
    "Uttargaya"
  ],
  "Sindhuli": [
    "Dudhauli",
    "Ghyanglekh",
    "Golanjor",
    "Hariharpurgadhi",
    "Kamalamai",
    "Marin",
    "Phikkal",
    "Sunkoshi",
    "Tinpatan"
  ],
  "Sindhupalchok": [
    "Bahrabise",
    "Balephi",
    "Bhotekoshi",
    "Chautara Sangachowkgadi",
    "Helambu",
    "Indrawati",
    "Jugal",
    "Lisankhu",
    "Melamchi",
    "Panchpokhari",
    "Sunkoshi",
    "Tripurasundari"
  ],
  "Baglung": [
    "Badigad",
    "Baglung",
    "Bareng",
    "Dhorpatan",
    "Galkot",
    "Jaimuni",
    "Khathekhola",
    "Nishi Khola",
    "Taman Khola",
    "Tara Khola"
  ],
  "Gorkha": [
    "Aarughat",
    "Ajirkot",
    "Bhimsen Thapa",
    "Chumnubri",
    "Dharche",
    "Gandaki",
    "Gorkha",
    "Palungtar",
    "Sahid Lakhan",
    "Siranchowk",
    "Sulikot"
  ],
  "Kaski": [
    "Annapurna",
    "Machhapuchchhre",
    "Madi",
    "Pokhara",
    "Rupa"
  ],
  "Lamjung": [
    "Besisahar",
    "Dordi",
    "Dudhpokhari",
    "Kwhlosothar",
    "Madhya Nepal",
    "Marsyangdi",
    "Rainas",
    "Sundarbazar"
  ],
  "Manang": [
    "Chame",
    "Manang Ngisyang",
    "NarpaBhumi",
    "Nason"
  ],
  "Mustang": [
    "Barhagaun Muktichhetra",
    "Gharpajhong",
    "Lo-Ghekar Damodarkunda",
    "Lomanthang",
    "Thasang"
  ],
  "Myagdi": [
    "Annapurna",
    "Beni",
    "Dhaulagiri",
    "Malika",
    "Mangala",
    "Raghuganga"
  ],
  "Nawalpur": [
    "Baudikali",
    "Binayi Tribeni",
    "Bulingtar",
    "Devachuli",
    "Gaindakot",
    "Hupsekot",
    "Kawasoti",
    "Madhya Bindu"
  ],
  "Parbat": [
    "Bihadi",
    "Jaljala",
    "Kushma",
    "Mahashila",
    "Modi",
    "Paiyun",
    "Phalewas"
  ],
  "Syangja": [
    "Aandhikhola",
    "Arjun Chaupari",
    "Bheerkot",
    "Biruwa",
    "Chapakot",
    "Galyang",
    "Harinas",
    "Kaligandaki",
    "Phedikhola",
    "Putalibazar",
    "Waling"
  ],
  "Tanahun": [
    "AnbuKhaireni",
    "Bandipur",
    "Bhanu",
    "Bhimad",
    "Byas",
    "Devghat",
    "Ghiring",
    "Myagde",
    "Rishing",
    "Suklagandaki"
  ],
  "Kapilvastu": [
    "Banganga",
    "Bijaynagar",
    "Buddhabhumi",
    "Kapilvastu",
    "Krishnanagar",
    "Maharajgunj",
    "Mayadevi",
    "Shivaraj",
    "Suddhodan",
    "Yashodhara"
  ],
  "Parasi": [
    "Bardaghat",
    "Palhi Nandan",
    "Pratappur",
    "Ramgram",
    "Sarawal",
    "Sunwal",
    "Susta"
  ],
  "Rupandehi": [
    "Butwal",
    "Devdaha",
    "Gaidahawa",
    "Kanchan",
    "Kotahimai",
    "Lumbini Sanskritik",
    "Marchawari",
    "Mayadevi",
    "Omsatiya",
    "Rohini",
    "Sainamaina",
    "Sammarimai",
    "Siddharthanagar",
    "Siyari",
    "Suddodhan",
    "Tilottama"
  ],
  "Arghakhanchi": [
    "Bhumikasthan",
    "Chhatradev",
    "Malarani",
    "Panini",
    "Sandhikharka",
    "Sitganga"
  ],
  "Gulmi": [
    "Chandrakot",
    "Chhatrakot",
    "Dhurkot",
    "Gulmidarbar",
    "Isma",
    "Kaligandaki",
    "Madane",
    "Malika",
    "Musikot",
    "Resunga",
    "Rurukshetra",
    "Satyawati"
  ],
  "Palpa": [
    "Bagnaskali",
    "Mathagadhi",
    "Nisdi",
    "Purbakhola",
    "Rainadevi Chhahara",
    "Rambha",
    "Rampur",
    "Ripdikot",
    "Tansen",
    "Tinahu"
  ],
  "Dang": [
    "Babai",
    "Banglachuli",
    "Dangisharan",
    "Gadhawa",
    "Ghorahi",
    "Lamahi",
    "Rajpur",
    "Rapti",
    "Shantinagar",
    "Tulsipur"
  ],
  "Pyuthan": [
    "Ayirawati",
    "Gaumukhi",
    "Jhimruk",
    "Mallarani",
    "Mandavi",
    "Naubahini",
    "Pyuthan",
    "Sarumarani",
    "Sworgadwari"
  ],
  "Rolpa": [
    "GangaDev",
    "Lungri",
    "Madi",
    "Pariwartan",
    "Rolpa",
    "Runtigadi",
    "Sunchhahari",
    "Sunil Smiriti",
    "Thawang",
    "Triveni"
  ],
  "Eastern Rukum": [
    "Bhume",
    "Putha Uttarganga",
    "Sisne"
  ],
  "Banke": [
    "Baijanath",
    "Duduwa",
    "Janaki",
    "Khajura",
    "Kohalpur",
    "Narainapur",
    "Nepalgunj",
    "Rapti-Sonari"
  ],
  "Bardiya": [
    "Badhaiyatal",
    "Barbardiya",
    "Basgadhi",
    "Geruwa",
    "Gulariya",
    "Madhuwan",
    "Rajapur",
    "Thakurbaba"
  ],
  "Western Rukum": [
    "Aathabiskot",
    "Banphikot",
    "Chaurjahari",
    "Musikot",
    "SaniBheri",
    "Triveni"
  ],
  "Salyan": [
    "Bagchaur",
    "Bangad Kupinde",
    "Chhatreshwari",
    "Darma",
    "Kalimati",
    "Kapurkot",
    "Kumakh",
    "Shaarda",
    "Siddha Kumakh",
    "Triveni"
  ],
  "Dolpa": [
    "Chharka Tongsong",
    "Dolpo Buddha",
    "Jagadulla",
    "Kaike",
    "Mudkechula",
    "She Phoksundo",
    "Thuli Bheri",
    "Tripurasundari"
  ],
  "Humla": [
    "Adanchuli",
    "Chankheli",
    "Kharpunath",
    "Namkha",
    "Sarkegad",
    "Simkot",
    "Tanjakot"
  ],
  "Jumla": [
    "Chandannath",
    "Guthichaur",
    "Hima",
    "Kanaka Sundari",
    "Patarasi",
    "Sinja",
    "Tatopani",
    "Tila"
  ],
  "Kalikot": [
    "Khandachakra",
    "Mahawai",
    "Narharinath",
    "Pachaljharana",
    "Palata",
    "Raskot",
    "Sanni Triveni",
    "Shubha Kalika",
    "Tilagufa"
  ],
  "Mugu": [
    "Chhayanath Rara",
    "Khatyad",
    "Mugum Karmarong",
    "Soru"
  ],
  "Surkhet": [
    "Barahatal",
    "Bheriganga",
    "Birendranagar",
    "Chaukune",
    "Chingad",
    "Gurbhakot",
    "Lekbeshi",
    "Panchapuri",
    "Simta"
  ],
  "Dailekh": [
    "Aathabis",
    "Bhagawatimai",
    "Bhairabi",
    "Chamunda Bindrasaini",
    "Dullu",
    "Dungeshwar",
    "Gurans",
    "Mahabu",
    "Narayan",
    "Naumule",
    "Thantikandh"
  ],
  "Jajarkot": [
    "Barekot",
    "Bheri",
    "Chhedagad",
    "Junichande",
    "Kuse",
    "Nalgad",
    "Shivalaya"
  ],
  "Darchula": [
    "Apihimal",
    "Duhun",
    "Lekam",
    "Mahakali",
    "Malikarjun",
    "Marma",
    "Naugad",
    "Shailyashikhar",
    "Vyans"
  ],
  "Bajhang": [
    "Bitthadchir",
    "Bungal",
    "Chhabis Pathibhera",
    "Durgathali",
    "Jayaprithvi",
    "Kedarsyu",
    "Khaptadchhanna",
    "Masta",
    "Saipal",
    "Surma",
    "Talkot",
    "Thalara"
  ],
  "Bajura": [
    "Badimalika",
    "Budhiganga",
    "Budhinanda",
    "Gaumul",
    "Himali",
    "Jagannath",
    "Khaptad Chhededaha",
    "Swami Kartik Khapar",
    "Triveni"
  ],
  "Baitadi": [
    "Dashrathchanda",
    "Dilashaini",
    "Dogdakedar",
    "Melauli",
    "Pancheshwar",
    "Patan",
    "Purchaudi",
    "Shivanath",
    "Sigas",
    "Surnaya"
  ],
  "Doti": [
    "Aadarsha",
    "Badikedar",
    "Bogatan-Phudsil",
    "Dipayal Silgadhi",
    "Jorayal",
    "K.I.Singh",
    "Purbichauki",
    "Sayal",
    "Shikhar"
  ],
  "Achham": [
    "Bannigadi Jayagad",
    "Chaurpati",
    "Dhakari",
    "Kamalbazar",
    "Mangalsen",
    "Mellekh",
    "Panchadewal Binayak",
    "Ramaroshan",
    "Sanfebagar",
    "Turmakhand"
  ],
  "Dadeldhura": [
    "Aalitaal",
    "Ajaymeru",
    "Amargadhi",
    "Bhageshwar",
    "Ganyapadhura",
    "Navadurga",
    "Parshuram"
  ],
  "Kanchanpur": [
    "Bedkot",
    "Belauri",
    "Beldandi",
    "Bhimdatta",
    "Krishnapur",
    "Laljhadi",
    "Mahakali",
    "Punarbas",
    "Shuklaphanta"
  ],
  "Kailali": [
    "Bardagoriya",
    "Bhajni",
    "Chure",
    "Dhangadhi",
    "Gauriganga",
    "Ghodaghodi",
    "Godawari",
    "Janaki",
    "Joshipur",
    "Kailari",
    "Lamkichuha",
    "Mohanyal",
    "Tikapur"
  ]
};
